repository: "hokudaianime/hokudaianime.github.io"
plugins:
  - "jekyll-seo-tag"

title: "北海道大学アニメーション研究会 HAL 公式Webサイト"
locale: "ja_JP"
twitter:
  username: "hokudai_anime"
  card: "summary"
social:
  name: "北海道大学アニメーション研究会"
  links:
    - "https://x.com/hokudai_anime"
    - "https://www.youtube.com/@hokudai_anime"
    - "https://www.instagram.com/hokudai_anime/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/img/ogp.png"