services:
  app:
    image: jekyll/jekyll:pages
    command:
      - bash 
      - -c
      - "gem install webrick && gem install jekyll-seo-tag && jekyll serve --force_polling"
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000